repos:
  # Ruff (Python linter & formatter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix]   # Autofix
      - id: ruff-format

  # nbstripout (clear jupyter output)
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
